stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs 
    - npm install
    - npm run build

deploy:
  tags: [websrv2]
  stage: deploy
  script:
    - npm install 
    - npm run build
    - sudo cp -R public /var/www/blog-fork
    - sudo systemctl restart nginx