---

- name: Deploy a new version of my blog
  hosts: yunohost-private-stable
  vars:
    webapp_directory: /var/www/webapp_richard/tgarcia.ch_
  tasks:
    - name: Compiling pug files
      shell: npm run build
      delegate_to: localhost

    - name: Copy those files
      synchronize:
        src: public/
        dest: "{{webapp_directory}}"
        delete: yes
        recursive: yes

    - name: Change file ownership, group and permissions
      file:
        path: "{{webapp_directory}}/*"
        owner: foo
        group: foo
        mode: '0644'
        recurse: yes

    - name: Reload nginx, in all cases
      systemd:
        name: nginx
        state: reloaded

    - name: Get the checksum of the index file
      stat:
        path: public/index.html
        checksum_algorithm: sha256
      register: checksum

    - name: Download file with check (sha256)
      get_url:
        url: https://tgarcia.ch
        dest: /tmp/
        checksum: "sha256:{{ checksum.checksum }}"